[package]
name = "ffinterp"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nalgebra = "0.34.1"
# For numeric traits such as Float
num = "0.4.3"
# Used for easy data parallelism 
rayon = "1.11.0"
# For Julia bindings
jlrs = { version = "0.22.1", features = ["ccall", "jlrs-derive"], optional = true }
# For Python bindings
pyo3 = { version = "0.27.2", features = [ "abi3-py38" ], optional = true }
numpy = { version = "0.27.1", optional = true }
# Optional CUDA dependencies
cust = { git = "https://github.com/rust-gpu/rust-cuda", rev = "7fa76f3d717038a92c90bf4a482b0b8dd3259344", optional = true }
kernels = { path = "kernels", optional = true }

[build-dependencies]
cuda_builder = { git = "https://github.com/rust-gpu/rust-cuda", rev = "7fa76f3d717038a92c90bf4a482b0b8dd3259344", features = ["rustc_codegen_nvvm"], optional = true }

[features]
cuda = [ "dep:cust", "dep:kernels", "dep:cuda_builder" ]
julia = [ "dep:jlrs" ]
python = [ "dep:pyo3", "dep:numpy" ]

[dev-dependencies]
# Used for benchmarking
criterion = "0.7" 
assert_approx_eq = "1.1.0"
# For plotting in the examples
egui_plot = "0.34.0"
eframe = "0.33.2"

[[bench]]
name = "interpolation_bench"
harness = false
